# Generated by Django 5.1.7 on 2025-03-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asl_sign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aslsign',
            name='image_path',
            field=models.CharField(max_length=255),
        ),
    ]
