# Generated by Django 4.2.20 on 2025-03-29 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AIPlanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='AIPlanner.course'),
        ),
    ]
