# Generated by Django 5.1.7 on 2025-03-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='quiz_images/')),
                ('option1', models.CharField(max_length=255)),
                ('option1_image', models.ImageField(blank=True, null=True, upload_to='quiz_images/')),
                ('option2', models.CharField(max_length=255)),
                ('option2_image', models.ImageField(blank=True, null=True, upload_to='quiz_images/')),
                ('option3', models.CharField(max_length=255)),
                ('option3_image', models.ImageField(blank=True, null=True, upload_to='quiz_images/')),
                ('option4', models.CharField(max_length=255)),
                ('option4_image', models.ImageField(blank=True, null=True, upload_to='quiz_images/')),
                ('correct_answer', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('High', 'High Talented')], default='Beginner', max_length=20)),
            ],
        ),
    ]
