# Generated by Django 5.1.7 on 2025-03-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordMatchQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='word_match/')),
            ],
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='game_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('word_match', 'Word Match')], default='quiz', max_length=20),
        ),
    ]
